# Generated by Django 4.2.3 on 2023-08-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FashionForEveryone", "0002_alter_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="user_img"),
        ),
    ]
