# Generated by Django 4.2.3 on 2023-08-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FashionForEveryone", "0003_alter_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="user_img/"),
        ),
    ]
