# Generated by Django 4.2.3 on 2023-08-09 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FashionForEveryone", "0004_alter_profile_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                (
                    "title",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("description", models.TextField()),
                ("img", models.ImageField(upload_to="news_img/")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("date_time_of_published", models.DateTimeField(auto_now_add=True)),
                (
                    "to_photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FashionForEveryone.news",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_time_of_published"],
            },
        ),
    ]
