# Generated by Django 4.2.3 on 2023-08-09 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FashionForEveryone", "0005_news_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=50, validators=[django.core.validators.MinLengthValidator(3)]
            ),
        ),
    ]
