# Generated by Django 4.2.3 on 2023-08-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FashionForEveryone", "0007_comment_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=2000),
        ),
    ]
