# Generated by Django 4.2.3 on 2023-08-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FashionForEveryone", "0008_alter_comment_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=5000)),
            ],
        ),
    ]
